Repository MessageKit/MessageKit, pull requests merged in 2020-06, with the labels that each got.

#1372 Remove CircleCI badge from README.md #trivial
  .github/workflows/ci_pr_example.yml
  .github/workflows/ci_pr_framework.yml
  .github/workflows/ci_pr_tests.yml
  .github/workflows/danger.yml
  README.md
Labels: infrastructure

#1367 ci: Checkout with depth to fix Danger #trivial
  .github/workflows/danger.yml
Labels: infrastructure

#1396 FIxed slack link in CONTRIBUTING.md resolved #1395
  CONTRIBUTING.md
Labels: documentation

#1310 Adds LinkPreview support to MessageKit
  CHANGELOG.md
  Example/Sources/Data Generation/SampleData.swift
  Example/Sources/Models/MockMessage.swift
  MessageKit.xcodeproj/project.pbxproj
  README.md
  Sources/Controllers/MessagesViewController.swift
  Sources/Layout/LinkPreviewMessageSizeCalculator.swift
  Sources/Layout/MessagesCollectionViewFlowLayout.swift
  Sources/Layout/MessagesCollectionViewLayoutAttributes.swift
  Sources/Models/ConcreteMessage.swift
  Sources/Models/LinkPreviewFonts.swift
  Sources/Models/MessageKind.swift
  Sources/Protocols/LinkItem.swift
  Sources/Protocols/MessagesDisplayDelegate.swift
  Sources/Views/Cells/LinkPreviewMessageCell.swift
  Sources/Views/LinkPreviewView.swift
  Sources/Views/MessagesCollectionView.swift
  Tests/ControllersTest/MessagesViewControllerTests.swift
  Tests/Mocks/MockMessage.swift
Labels: API breaking, enhancement
