Repository MessageKit/MessageKit, pull requests merged in 2020-02, with the labels that each got.

#1204 Update QuickStart.md
  Documentation/QuickStart.md
Labels: documentation

#1201 Fixes @available annotations to correctly report deprecation/obsoletion 👻
  Sources/Models/Sender.swift
  Sources/Supporting/MessageInputBar.swift
Labels: documentation, enhancement

#1248 Add CHANGELOG entries for PR #1201
  CHANGELOG.md
Labels: documentation

#1253 Update InputBarAccessoryView to 4.3.2, edit Cartfile to allow < v5.0.0
  Cartfile
  Cartfile.resolved
Labels: carthage

#1256 Update Circle CI PR tests to include cache for pods
  .circleci/config.yml
  MessageKit.podspec
Labels: development

#1257 Add PR tests by Danger and SwiftLint
  .github/workflows/danger.yml
  Dangerfile
  Gemfile
Labels: development
