Repository MessageKit/MessageKit, pull requests merged in 2020-03, with the labels that each got.

#1266 Fix for issue 1265
  Sources/Views/TypingIndicator.swift
Labels: confirmed bug

#1274 (Infra) Switch to Gihub Actions, update Danger #trivial
  .github/workflows/ci_pr_example.yml
  .github/workflows/ci_pr_framework.yml
  .github/workflows/ci_pr_tests.yml
  .github/workflows/danger.yml
  .swiftlint.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  GitHubActions/build.sh
  Sources/Models/AccessoryPosition.swift
Labels: infrastructure

#1281 Added COYO Engage to the apps list
  README.md
Labels: documentation

#1278 Fix image view tap gesture handler.
  Sources/Views/Cells/MediaMessageCell.swift
Labels: confirmed bug, priority: high

#1261 Drop iOS 9 and iOS 10, update example project
  .github/workflows/ci_pr_example.yml
  .swift-version
  CHANGELOG.md
  Example/ChatExample.xcodeproj/project.pbxproj
  Example/ChatExample.xcodeproj/xcshareddata/xcschemes/ChatExample.xcscheme
  Example/ChatExample.xcodeproj/xcshareddata/xcschemes/ChatExampleUITests.xcscheme
  Example/Podfile
  Example/Podfile.lock
  Example/Sources/View Controllers/LaunchViewController.swift
  Example/Sources/View Controllers/NavigationController.swift
  Example/UITests/ChatExampleUITests.swift
  LICENSE.md
  MessageKit.podspec
  MessageKit.xcodeproj/project.pbxproj
  README.md
  Sources/Controllers/MessagesViewController+Keyboard.swift
  Sources/Controllers/MessagesViewController.swift
  Tests/ControllersTest/MessagesViewControllerSpec.swift
Labels: infrastructure

#1295 Fix caching for CI #trivial
  .github/workflows/ci_pr_example.yml
  .github/workflows/ci_pr_framework.yml
  .github/workflows/ci_pr_tests.yml
  .github/workflows/danger.yml
Labels: infrastructure
